export const movieList = [
    {
      id: 1,
      title: "The Shawshank Redemption",
      cast: [
        "Tim Robbins",
        "Morgan Freeman",
        "Bob Gunton",
        "William Sadler",
        "Clancy Brown",
        "Gil Bellows",
        "Mark Rolston",
        "James Whitmore",
        "Jeffrey DeMunn",
        "Larry Brandenburg",
        "Neil Giuntoli",
        "Brian Libby",
        "David Proval",
        "Joseph Ragno",
        "Jude Ciccolella",
      ],
      director: "Frank Darabont",
      storyline:
        "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      year: "1994",
      genre: ["Drama"],
      rating: 9.3,
      created_at: "2020-07-28T05:34:06.168Z",
      updated_at: "2020-07-28T05:34:06.168Z",
    },
    {
      id: 2,
      title: "The Godfather",
      cast: [
        "Marlon Brando",
        "Al Pacino",
        "James Caan",
        "Richard S. Castellano",
        "Robert Duvall",
        "Sterling Hayden",
        "John Marley",
        "Richard Conte",
        "Al Lettieri",
        "Diane Keaton",
        "Abe Vigoda",
        "Talia Shire",
        "Gianni Russo",
        "John Cazale",
        "Rudy Bond",
      ],
      director: "Francis Ford Coppola",
      storyline:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      year: "1972",
      genre: ["Crime"],
      rating: 9.2,
      created_at: "2020-07-28T05:34:06.179Z",
      updated_at: "2020-07-28T05:34:06.179Z",
    },
    {
      id: 3,
      title: "The Godfather: Part II",
      cast: [
        "Al Pacino",
        "Robert Duvall",
        "Diane Keaton",
        "Robert De Niro",
        "John Cazale",
        "Talia Shire",
        "Lee Strasberg",
        "Michael V. Gazzo",
        "G.D. Spradlin",
        "Richard Bright",
        "Gastone Moschin",
        "Tom Rosqui",
        "Bruno Kirby",
        "Frank Sivero",
        "Francesca De Sapio",
      ],
      director: "Francis Ford Coppola",
      storyline:
        "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
      year: "1974",
      genre: ["Crime"],
      rating: 9.0,
      created_at: "2020-07-28T05:34:06.188Z",
      updated_at: "2020-07-28T05:34:06.188Z",
    },
    {
      id: 4,
      title: "The Dark Knight",
      cast: [
        "Christian Bale",
        "Heath Ledger",
        "Aaron Eckhart",
        "Michael Caine",
        "Maggie Gyllenhaal",
        "Gary Oldman",
        "Morgan Freeman",
        "Monique Gabriela Curnen",
        "Ron Dean",
        "Cillian Murphy",
        "Chin Han",
        "Nestor Carbonell",
        "Eric Roberts",
        "Ritchie Coster",
        "Anthony Michael Hall",
      ],
      director: "Christopher Nolan",
      storyline:
        "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      year: "2008",
      genre: ["Action"],
      rating: 9.0,
      created_at: "2020-07-28T05:34:06.196Z",
      updated_at: "2020-07-28T05:34:06.196Z",
    },
    {
      id: 5,
      title: "12 Angry Men",
      cast: [
        "Martin Balsam",
        "John Fiedler",
        "Lee J. Cobb",
        "E.G. Marshall",
        "Jack Klugman",
        "Edward Binns",
        "Jack Warden",
        "Henry Fonda",
        "Joseph Sweeney",
        "Ed Begley",
        "George Voskovec",
        "Robert Webber",
      ],
      director: "Sidney Lumet",
      storyline:
        "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
      year: "1957",
      genre: ["Crime"],
      rating: 8.9,
      created_at: "2020-07-28T05:34:06.203Z",
      updated_at: "2020-07-28T05:34:06.203Z",
    },
    {
      id: 6,
      title: "Schindler's List",
      cast: [
        "Liam Neeson",
        "Ben Kingsley",
        "Ralph Fiennes",
        "Caroline Goodall",
        "Jonathan Sagall",
        "Embeth Davidtz",
        "Malgorzata Gebel",
        "Shmuel Levy",
        "Mark Ivanir",
        "Béatrice Macola",
        "Andrzej Seweryn",
        "Friedrich von Thun",
        "Krzysztof Luft",
        "Harry Nehring",
        "Norbert Weisser",
      ],
      director: "Steven Spielberg",
      storyline:
        "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
      year: "1993",
      genre: ["Biography"],
      rating: 8.9,
      created_at: "2020-07-28T05:34:06.212Z",
      updated_at: "2020-07-28T05:34:06.212Z",
    },
    {
      id: 7,
      title: "The Lord of the Rings: The Return of the King",
      cast: [
        "Noel Appleby",
        "Ali Astin",
        "Sean Astin",
        "David Aston",
        "John Bach",
        "Sean Bean",
        "Cate Blanchett",
        "Orlando Bloom",
        "Billy Boyd",
        "Sadwyn Brophy",
        "Alistair Browning",
        "Marton Csokas",
        "Richard Edge",
        "Jason Fitch",
        "Bernard Hill",
      ],
      director: "Peter Jackson",
      storyline:
        "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      year: "2003",
      genre: ["Adventure"],
      rating: 8.9,
      created_at: "2020-07-28T05:34:06.219Z",
      updated_at: "2020-07-28T05:34:06.219Z",
    },
    {
      id: 8,
      title: "Pulp Fiction",
      cast: [
        "Tim Roth",
        "Amanda Plummer",
        "Laura Lovelace",
        "John Travolta",
        "Samuel L. Jackson",
        "Phil LaMarr",
        "Frank Whaley",
        "Burr Steers",
        "Bruce Willis",
        "Ving Rhames",
        "Paul Calderon",
        "Bronagh Gallagher",
        "Rosanna Arquette",
        "Eric Stoltz",
        "Uma Thurman",
      ],
      director: "Quentin Tarantino",
      storyline:
        "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      year: "1994",
      genre: ["Crime"],
      rating: 8.9,
      created_at: "2020-07-28T05:34:06.232Z",
      updated_at: "2020-07-28T05:34:06.232Z",
    },
    {
      id: 9,
      title: "The Good, the Bad and the Ugly",
      cast: [
        "Eli Wallach",
        "Clint Eastwood",
        "Lee Van Cleef",
        "Aldo Giuffrè",
        "Luigi Pistilli",
        "Rada Rassimov",
        "Enzo Petito",
        "Claudio Scarchilli",
        "John Bartha",
        "Livio Lorenzon",
        "Antonio Casale",
        "Sandro Scarchilli",
        "Benito Stefanelli",
        "Angelo Novi",
        "Antonio Casas",
      ],
      director: "Sergio Leone",
      storyline:
        "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
      year: "1966",
      genre: ["Western"],
      rating: 8.8,
      created_at: "2020-07-28T05:34:06.242Z",
      updated_at: "2020-07-28T05:34:06.242Z",
    },
  ];